src/connection.rs, src/error.rs, src/ibase.rs, src/lib.rs, src/row.rs, src/statement.rs, src/transaction.rs, src/xsqlda.rs
I've also changed some of the types in the `ibase` module back to the originals generated by bindgen, i think it's better
to not change the autogenerated code to simplify moving to newer versions of the fbclient, and the module
could be autogenerated if we can make static linking work, what do you think?
=> Minimized use of unsafe and a bit of changes to the api

src/params.rs, src/row.rs, src/xsqlda.rs
Now the only `unsafe` blocks left are the calls to fbclient functions and the allocation / de-allocation of the xsqlda, which i don't know how to remove because of the variable length.
=> Couple of improvements for the `row`, `params` and `xsqld` modules

src/row.rs
Related to https://github.com/fernandobatels/rsfbclient/issues/11.
=> Fixed wrong BIGINT buffering. (Fix #11)

.github/workflows/testing_changes.yml, rsfbclient-native/Cargo.toml, rsfbclient-native/build.rs, src/tests/mod.rs
Continued from #31.
What's missing yet:
- `cargo tarpaulin` is disabled because it's failing on some path issue.
- `embedded` test case is not enabled.
=> ci: run tests on windows

README.md, rsfbclient-native/src/connection.rs, rsfbclient-native/src/params.rs, rsfbclient-native/src/row.rs
All tests passing (embedded version not tested)
Cpu tested: `Cortex-A53`, architecture `aarch64` with linux kernel `5.8.0`
Native fbclient library version `2.5.8`
Related to #41
=> Working on the Raspberry Pi 3

rsfbclient-core/src/charset.rs, rsfbclient-native/src/lib.rs, rsfbclient-native/src/params.rs, rsfbclient-native/src/row.rs, rsfbclient-native/src/varchar.rs, rsfbclient-rust/src/consts.rs, rsfbclient-rust/src/wire.rs, src/tests/row.rs
In the first commit, changes the encoding and decoding code to avoid copying data where possible by using the `Cow` type.
In the second, change the way data is sent / received from the `fbclient` library to make sure all data is properly aligned by allocating the exact data type expected in the rust side, instead of a byte buffer in all cases.
=> Refactorations

src/tests/mod.rs, src/tests/transaction.rs
Before I go create some separate issues: should these tests be expected to work?
I get
``` 
Error: Sql { msg: "unsuccessful metadata update\nobject TABLE \"RSFBCLIENT_TEST_TRANSACTION\" is in use", code: -607 }
```
=> add tests for struct Transaction

src/connection/mod.rs, src/query.rs, src/transaction.rs
Removed lifetime and trait bounds from the trait itself.
Closes #51
=> Simplify `Queryable` trait

Cargo.toml, rsfbclient-core/src/connection.rs, rsfbclient-core/src/date_time.rs, rsfbclient-core/src/error.rs, rsfbclient-core/src/lib.rs, rsfbclient-core/src/params.rs, rsfbclient-core/src/row.rs, rsfbclient-native/Cargo.toml, rsfbclient-native/src/connection.rs, rsfbclient-native/src/params.rs, rsfbclient-native/src/row.rs, rsfbclient-rust/Cargo.toml, rsfbclient-rust/src/blr.rs, rsfbclient-rust/src/client.rs, rsfbclient-rust/src/wire.rs, src/lib.rs, src/tests/params.rs, src/tests/transaction.rs
Simplifications to the api to allow users to easily match the `value` property of the `Column` struct when using named columns
=> Named columns refactor

rsfbclient-core/src/params.rs, rsfbclient-derive/src/lib.rs, rsfbclient-rust/src/client.rs, src/connection/mod.rs, src/query.rs, src/transaction.rs
Is what I said about `Option<T>` on `IntoParams` correct?
Please additionally add a doc comment for the derive macro, especially since it is referenced in `params.rs` and now `query.rs` docs.
=> doc and identifier modifications

rsfbclient-core/src/connection.rs, rsfbclient-native/src/connection.rs, rsfbclient-native/src/ibase.rs, rsfbclient-rust/src/client.rs, rsfbclient-rust/src/wire.rs, src/connection/mod.rs, src/query.rs, src/statement.rs, src/tests/row.rs, src/transaction.rs
Started the support for 'insert .. returing' stmt and 'execute block'.
Now it's basically WIP code
---------
TODO:
- native
- pure
- native
- pure
=> Support for stmt execution without cursor

.github/workflows/testing_changes.yml
This will change the CI in a few ways.
1. doesn't run the CI on push with only workflow changes
2. checks if CI run needed when a draft PR becomes ready for review
3. checks if CI run needed when a label is added to a PR. in most cases this does not cause the CI to run but it does cause the workflow itself to run.
4. adds detection for draft status of PRs. By default the CI is skipped for draft PRs.
5. adds detection for label 'prevent-ci' on PRs (draft or not) to prevent running CI.
6. adds detection for label 'force-ci' which overrides all of the above and forces CI to be run on subsequent changes (excluding label additions)
7. force runs the CI once when the 'force-ci' label is added to a PR
note that *all* label additions trigger the workflow, but this configuration will only allow …
=> add opt-out and opt-in options to ci using labels

rsfbclient-core/src/params.rs, rsfbclient-native/src/connection.rs, rsfbclient-native/src/params.rs, rsfbclient-native/src/varchar.rs, rsfbclient-rust/src/client.rs, rsfbclient-rust/src/wire.rs
The ones at `rsfbclient-rust/src/client.rs` are specially important, as they are not really that difficult to panic.
Don't know how i did not see them before.
=> Removed some `unwrap` uses

src/connection/mod.rs, src/transaction.rs
Utilization of `ManuallyDrop` replaced by `mem::forget` due the [new rust 1.48](https://doc.rust-lang.org/src/core/mem/manually_drop.rs.html#65) recommendation, avoiding warnings.
More info about this rust change in [f3024073f92b15d38b42241e65067f0ba796896c](https://github.com/rust-lang/rust/commit/f3024073f92b15d38b42241e65067f0ba796896c), on std lib rust.
=> ManuallyDrop droped

.github/workflows/security_audit.yml
This is a minor caveat from using a scheduled action for running the security audit.
This adds a condition for skipping the security audit action/workflow on forked GitHub repositories for avoiding polluting logs and notifications.
=> Avoid running security audit on forked repos

rsfbclient-native/build.rs
Removed a 'rerun-if' command from 'build.rs' of rsfbclient-
native. The command was forcing the rsfbclient and rsfbclient-native
always recompile, due to the non-existence of the tests folder on
rsfbclient-native.
=> Unnecessary command removed from build.rs

examples/createdb.rs, rsfbclient-core/src/connection.rs, rsfbclient-diesel/src/tests/types.rs, rsfbclient-native/src/connection.rs, rsfbclient-native/src/ibase.rs, rsfbclient-native/src/params.rs, rsfbclient-native/src/row.rs, rsfbclient-rust/src/blr.rs, rsfbclient-rust/src/client.rs, rsfbclient-rust/src/wire.rs, src/connection/builders/builder_native.rs, src/connection/builders/builder_pure_rust.rs, src/connection/mod.rs, src/tests/database.rs, src/tests/mod.rs, src/tests/row.rs
Add support for `create_database()` method, aka `isc_create_database`:
- native
- pure rust
=> create_database() support

examples/insert.rs, rsfbclient-derive/src/lib.rs, src/tests/params.rs
Automatic implementation of IntoParams using derive changed to avoid using the 'use' keyword.
Without this, we cannot use the derive in more than one struct in the same module, due to the multiple imports.
New test created and example fixed. #123
=> IntoParams derive fixed

.github/workflows/testing_changes.yml, examples/events.rs, r2d2_firebird/src/lib.rs, rsfbclient-core/src/connection.rs, rsfbclient-native/src/connection.rs, rsfbclient-native/src/ibase.rs, src/connection/mod.rs, src/connection/simple.rs, src/events.rs, src/lib.rs
Firebird events support added. Now the users can listen for posted events by triggers and others.
Only for native client. The wire protocol is too complex to implement now.
Basically now we have `wait_for_event` method directly on the connection struct and a more complex solution with `listen_event` method from `RemoteEventManager`.
=> Firebird events support

rsfbclient-diesel/Cargo.toml, rsfbclient-native/src/row.rs, rsfbclient-rust/src/wire.rs, rsfbclient-rust/src/xsqlda.rs, src/tests/row.rs
Support for custom blob subtypes added.
Blob subtypes supported now:
- 1: TEXT
- 0: binary
- <= -1: custom
Issue #146
=> Custom blob subtypes

examples/createdb.rs, rsfbclient-core/src/connection.rs, rsfbclient-native/src/connection.rs, rsfbclient-rust/src/client.rs, rsfbclient-rust/src/wire.rs, src/connection/builders/builder_native.rs, src/connection/builders/builder_pure_rust.rs, src/connection/mod.rs, src/tests/connection.rs, src/tests/database.rs
The `dialect` connection builder options now are also applied on database creation, provided by `create_database` method. 
`no_db_trigger` option added on connection builder, applied on database connection, disabling the database triggers. Table triggers are no affected.
=> Dialect on create_database and no_db_trigger support

rsfbclient-native/src/varchar.rs, rsfbclient-native/src/xsqlda.rs
using slice::from_raw_parts to genereta a new slice with a mutable size. to avoid the new bound checking on get_unchecked and get_unchecked_mut
=> fix compatibility issues 

rsfbclient-native/src/params.rs, src/tests/params.rs, src/tests/row.rs
=> Fixed blobs greater than 65535 bytes

rsfbclient-core/src/row.rs, rsfbclient-native/src/row.rs, rsfbclient-rust/src/wire.rs, src/tests/row.rs
this trying to fix https://github.com/fernandobatels/rsfbclient/issues/163
=> add raw_type to column
